# Generated by Django 4.0.2 on 2022-02-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_name', models.CharField(max_length=200, null=True)),
                ('review', models.TextField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.maininfo')),
            ],
        ),
    ]
