# Generated by Django 4.0.2 on 2022-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='imdb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='rotTom',
            field=models.URLField(null=True),
        ),
    ]
