# Generated by Django 4.0.2 on 2022-02-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_maininfo_hero_img_alter_maininfo_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='des',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='hero_img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='imdb',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='post_img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='rotTom',
            field=models.URLField(),
        ),
    ]
