# Generated by Django 4.0.2 on 2022-02-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_maininfo_des_alter_maininfo_hero_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='hero_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='imdb',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='post_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='rotTom',
            field=models.URLField(null=True),
        ),
    ]
