# Generated by Django 4.0.2 on 2022-02-17 18:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_reviews_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='catgry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Anime', 'Anime'), ('Drama', 'Drama'), ('Web-Series', 'Web-Series'), ('Movies', 'Movies')], max_length=50, null=True),
        ),
    ]
