# Generated by Django 4.0.2 on 2022-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_maininfo_catgry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='catgry',
            field=models.CharField(choices=[('Anime', 'Anime'), ('Drama', 'Drama'), ('Web-Series', 'Web-Series'), ('Movies', 'Movies')], max_length=50, null=True),
        ),
    ]
