# Generated by Django 4.0.2 on 2022-02-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_catgry_maininfo_catgrys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='catgrys',
            field=models.ManyToManyField(blank=True, to='app.Catgry'),
        ),
    ]
