# Generated by Django 4.0.2 on 2022-02-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_maininfo_catgrys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='catgry',
        ),
    ]
